In [1]:
import numpy as np
vector = np.array([1,4,5,7,8,9,4,3,8,9,4])
print(vector)



# Cantidad de elementos del vector
print(len(vector))

# Indexacion del vector
print(vector[3])

# Actualizacion de valores del vector
vector[3]=50

# slicing del vector [indice_inicial:indice_fianl:paso]
print(vector[2:9])
print(vector[2:9:3])

# Ciclos
for valor in vector:
  print(valor)
     

[1 4 5 7 8 9 4 3 8 9 4]
11
7
[ 5 50  8  9  4  3  8]
[5 9 8]
1
4
5
50
8
9
4
3
8
9
4


In [10]:
vector1 = np.array([2,3,4])
vector2 = np.array([4,5,6])

resultado =np.dot(vector1,vector2)
print(resultado)

47


In [16]:

# Reshape para que sea de forma (2, 8)
matriz_reshape = matriz.reshape(2, 8)
print("Matriz con reshape (2, 8):")
print(matriz_reshape)


Matriz con reshape (2, 8):
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [17]:

import numpy as np
vectorUno = np.array([1, 2, 3])
vectorDos = np.array([4, 5, 6])

# Suma de vectores
suma = vectorUno + vectorDos
print(suma,"\n")

sumaDos = vectorUno + 6
print(sumaDos,"\n")


# Producto punto
producto = np.dot(vectorUno, vectorDos)
print(producto,"\n")

[5 7 9] 

[7 8 9] 

32 



In [2]:
import numpy as np

# 1. Crear un arreglo 3x3 de numpy con todas las entradas igual a True
arr1 = np.full((3, 3), True)
print(arr1)




[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
# 2. Reemplazar todos los números impares del siguiente arreglo por el valor de -1
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2[arr2 % 2 != 0] = -1
print(arr2)



[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
# 3. Convertir el siguiente arreglo 1D a un arreglo 2D
arr3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr3_2D = arr3.reshape(2, 5)  # Convertirlo a una matriz 2x5
print(arr3_2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
import pandas as pd

df_file_csv = pd.read_csv('./datos/CalificacionesTXT.csv')
df_file_csv.head()

ITEM NOMBRES  APELLIDOS        Programa     Genero Matematicas Español  \
0     1    Juan     García    Contabilidad  Masculino        1,66    2,19   
1     2   María      Pérez        Mercadeo   Femenino        3,21    2,54   
2     3   Pedro  Fernández        Sistemas  Masculino        3,10    3,11   
3     4     Ana    Sánchez  Administracion   Femenino         NaN    2,50   
4     5    Luis   González           Salud  Masculino        2,91    2,59   

  Ciencias Idiomas  
0     3,56    2,58  
1     1,98    3,76  
2     2,62    2,42  
3     3,66    1,93  
4     2,45     NaN